tennis/lib/tennis_web/router.ex
defmodule TennisWeb.Router do
  use TennisWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Phauxth.Authenticate)
    plug(Phauxth.Remember)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TennisWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/players", PlayerController)
    resources("/session", SessionController, only: [:new, :create, :delete])
    resources("/venues", VenueController)
    resources("/matches", MatchController)
  end

  # Other scopes may use custom stacks.
  # scope "/api", TennisWeb do
  #   pipe_through :api
  # end
end

tennis/lib/tennis_web/views/layout_view.ex
defmodule TennisWeb.LayoutView do
  use TennisWeb, :view
end

tennis/lib/tennis_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Tennis!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/bootstrap.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav class="nav nav-pills justify-content-end" role="navigation">
          <a class="nav-link" href="<%= page_path @conn, :index %>">Home</a>
          <%= if @current_user do %>
          <%= admin_link(@current_user, player_path(@conn, :index), "Users", ["nav-link"]) %>
          <a class="nav-link" href="<%= venue_path(@conn, :index) %>">Venues</a>
          <a class="nav-link" href="<%= player_path(@conn, :show, @current_user.id) %>"><%= @current_user.email %></a>
          <%= link "Logout", to: session_path(@conn, :delete, @current_user), method: :delete, class: "btn btn-primary col-auto" %>
          <% else %>
          <a class="nav-link" href="<%= player_path @conn, :new %>">New user</a>
          <a class="nav-link" href="<%= session_path @conn, :new %>">Login</a>
          <% end %>
        </nav>
      </header>

      <p class="alert alert-info mt-4" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>
    <script defer src="<%= static_path(@conn, "/js/bootstrap.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>